// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://stalqxemulkocihcmfnj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN0YWxxeGVtdWxrb2NpaGNtZm5qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA1MjQ4NjgsImV4cCI6MjA1NjEwMDg2OH0.LF1sFbphAFDaNxjdW9YmViVzpIjX3n9KwE75rtpJF1c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);